# Dockerfile.consumer
FROM node:latest

WORKDIR /usr/src/app

COPY package.json pnpm-lock.yaml ./

RUN npm install -g pnpm && pnpm install

COPY consumer.js ./
COPY consumer-app.js ./
COPY .env ./

CMD ["node", "consumer-app.js"]
