# Dockerfile.server
FROM node:latest

WORKDIR /usr/src/app

COPY package.json pnpm-lock.yaml ./

RUN npm install -g pnpm && pnpm install

COPY server.js ./
COPY producer.js ./
COPY .env ./

CMD ["node", "server.js"]
